"""
opportunities.py
Reads output/ai_insights.json (generated by ai.py) and provides
helper functions for the FastAPI backend and report generator.
Run ai.py first to generate the JSON.
"""
import os
import sys
import json
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database.models import SessionLocal, Opportunity


def load_insights():
    path = "output/ai_insights.json"
    if not os.path.exists(path):
        return {"gaps": [], "insights": {}}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def get_gaps():
    return load_insights().get("gaps", [])


def get_recommendations():
    return load_insights().get("insights", {}).get("content_recommendations", [])


def get_gap_analyses():
    return load_insights().get("insights", {}).get("gap_analyses", [])


def get_executive_summary():
    return load_insights().get("insights", {}).get("executive_summary", "")


def get_opportunities_from_db():
    db = SessionLocal()
    opps = db.query(Opportunity).order_by(Opportunity.competitor_count.desc()).all()
    db.close()
    return [
        {
            "id":                   o.id,
            "topic":                o.topics,
            "competitor_count":     o.competitor_count,
            "competitors_covering": o.competitor_name_covering,
            "suggested_title":      o.suggested_title,
            "reason":               o.reason,
        }
        for o in opps
    ]


if __name__ == "__main__":
    data = load_insights()
    if not data["gaps"]:
        print("No insights found. Run: python analysis/ai.py")
    else:
        print(f" {len(data['gaps'])} gaps, "
              f"{len(get_recommendations())} recommendations loaded")
        print(f"\nExecutive Summary:\n{get_executive_summary()}")
